import type { InterfaceCatalogEntry, RuntimeMode } from "../types/models.js";

const interfaceCatalog: InterfaceCatalogEntry[] = [
  {
    id: "nodes.list",
    method: "GET",
    path: "/api/nodes",
    owner: "portal",
    plane: "control",
    accessMode: "portal_only",
    summary: "聚合节点目录与节点健康摘要。",
    currentStatus: "固定由 Hub/Portal 聚合提供。",
  },
  {
    id: "sessions.list",
    method: "GET",
    path: "/api/session/list",
    owner: "portal",
    plane: "control",
    accessMode: "portal_only",
    summary: "聚合会话列表与跨节点摘要。",
    currentStatus: "固定由 Hub/Portal 聚合提供。",
  },
  {
    id: "events.stream",
    method: "WS",
    path: "/ws/events",
    owner: "portal",
    plane: "control",
    accessMode: "portal_only",
    summary: "控制面会话快照与 session-updated 事件流。",
    currentStatus: "固定统一入口，当前不进入 node-first。",
  },
  {
    id: "system.health.detail",
    method: "GET",
    path: "/api/system/health/detail",
    owner: "shared",
    plane: "control",
    accessMode: "portal_only",
    summary: "系统健康与运行模式摘要。",
    currentStatus: "Hub 返回聚合健康，single/node 返回本地健康。",
  },
  {
    id: "session.detail",
    method: "GET",
    path: "/api/session/:id/detail",
    owner: "node",
    plane: "data",
    accessMode: "node_first_read",
    summary: "单会话详情与运行态摘要。",
    currentStatus: "前端已进入 node-first 读取实验。",
  },
  {
    id: "codex.history",
    method: "GET",
    path: "/api/codex/history",
    owner: "node",
    plane: "data",
    accessMode: "node_first_read",
    summary: "读取目标节点上的历史会话摘要。",
    currentStatus: "前端已进入 node-first 读取实验。",
  },
  {
    id: "fs.list",
    method: "GET",
    path: "/api/fs/list",
    owner: "node",
    plane: "data",
    accessMode: "node_first_read",
    summary: "列目录，只读能力。",
    currentStatus: "前端已进入 node-first 读取实验。",
  },
  {
    id: "fs.file.read",
    method: "GET",
    path: "/api/fs/file",
    owner: "node",
    plane: "data",
    accessMode: "node_first_read",
    summary: "读文件，只读能力。",
    currentStatus: "前端已进入 node-first 读取实验。",
  },
  {
    id: "fs.file.download",
    method: "GET",
    path: "/api/fs/download",
    owner: "node",
    plane: "data",
    accessMode: "node_first_read",
    summary: "下载文件，只读能力。",
    currentStatus: "前端已进入 node-first 读取实验。",
  },
  {
    id: "goalGuard.templates",
    method: "GET",
    path: "/api/goal-guard/templates",
    owner: "node",
    plane: "data",
    accessMode: "node_first_read",
    summary: "读取 Goal Guard 模板。",
    currentStatus: "前端已进入 node-first 读取实验。",
  },
  {
    id: "goalGuard.debug",
    method: "GET",
    path: "/api/goal-guard/:sessionId/debug",
    owner: "node",
    plane: "data",
    accessMode: "node_first_read",
    summary: "读取 Goal Guard 调试详情。",
    currentStatus: "前端已进入 node-first 读取实验。",
  },
  {
    id: "terminal.websocket",
    method: "WS",
    path: "/ws/terminal/:sessionId",
    owner: "node",
    plane: "data",
    accessMode: "node_first_read",
    summary: "终端实时 websocket。",
    currentStatus: "已进入 direct_preferred + fallback gateway 第一版。",
  },
  {
    id: "session.create",
    method: "POST",
    path: "/api/session/create",
    owner: "portal",
    plane: "control",
    accessMode: "gateway_first_write",
    summary: "创建会话的控制面分发入口。",
    currentStatus: "当前固定统一入口。",
  },
  {
    id: "session.close",
    method: "POST",
    path: "/api/session/:id/close",
    owner: "portal",
    plane: "control",
    accessMode: "gateway_first_write",
    summary: "关闭会话的控制面分发入口。",
    currentStatus: "当前固定统一入口。",
  },
  {
    id: "session.rename",
    method: "POST",
    path: "/api/session/:id/rename",
    owner: "portal",
    plane: "control",
    accessMode: "gateway_first_write",
    summary: "重命名会话的控制面分发入口。",
    currentStatus: "当前固定统一入口。",
  },
  {
    id: "goalGuard.update",
    method: "PUT",
    path: "/api/goal-guard/:sessionId",
    owner: "portal",
    plane: "data",
    accessMode: "gateway_first_write",
    summary: "更新 Goal Guard 配置。",
    currentStatus: "当前写路径固定统一入口。",
  },
  {
    id: "goalGuard.overrideStop",
    method: "POST",
    path: "/api/goal-guard/:sessionId/override-stop",
    owner: "portal",
    plane: "data",
    accessMode: "gateway_first_write",
    summary: "强制停止 Goal Guard / 会话。",
    currentStatus: "当前写路径固定统一入口。",
  },
  {
    id: "fs.write",
    method: "PUT",
    path: "/api/fs/file",
    owner: "portal",
    plane: "data",
    accessMode: "gateway_first_write",
    summary: "文件内容写入。",
    currentStatus: "当前写路径固定统一入口。",
  },
  {
    id: "fs.create",
    method: "POST",
    path: "/api/fs/file | /api/fs/folder | /api/fs/upload | /api/fs/rename | /api/fs/delete",
    owner: "portal",
    plane: "data",
    accessMode: "gateway_first_write",
    summary: "文件系统变更类写操作。",
    currentStatus: "当前写路径固定统一入口。",
  },
];

export function listInterfaceCatalog(_runtimeMode: RuntimeMode): InterfaceCatalogEntry[] {
  return interfaceCatalog;
}
